### ISSUE TITLE
Cannot add route paths

### ISSUE THREAD

**Issue by stevaras** [crsandeep/simple-react-full-stack#23]
For example I'm going inside server/index.js and add: 
```
app.get('/about', (req, res) => {
  console.log('test');
});
```
And all I get is a "Cannot GET /about" message in the browser and nothing is shown in the server console. Does webpack overrides that or something? 
If I add app.get(/api/about) it will run the console log although I'll still see the "Cannot GET /about". 

How can I add get/post responses with this boilerplate? 

Thanks and sorry if my questions are irrelevant.

**Comment by crsandeep** [comment]
@stevaras when you run `npm run dev` or `yarn dev`, client and server gets started in 2 different ports. Client starts in 3000 and server starts in 8080. You are adding `/about` to server so you have to use port 8080 instead of 3000 http://localhost:8080/about. /api/about works because of webpack dev server. It routes any http://localhost:3000/api/about calls to http://localhost:8080/api/about. You can read here https://github.com/crsandeep/simple-react-full-stack#webpack-dev-server

**Comment by stevaras** [comment]
You are right. Sorry for opening this as an issue. 
I'm new to express and webpack and trying to figure it out a bit. 
Thanks for your reply :)
